import type { Metadata } from "next";

import { Toaster } from "sonner";
import { TRPCReactProvider } from "@/trpc/client";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <TRPCReactProvider> 
    <html lang="en">
      <body
        
      >
        <Toaster />
        {children}
      </body>
    </html>
    </TRPCReactProvider> 
  );
}
